version: '3.7'
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
        context: ./ 

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  mongodb:
    image: mongo:latest
    container_name: mongodb-service
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  caddy_data:
  caddy_config:
  mongodb_data:
